from enum import Enum


class MutatorType(str, Enum):
    """
    Enum for breaking the attack.
    """
    REPHRASE = "rephrase"
    RETOKENIZE = "retokenize"
    SUMMARIZE = "summarize"
    FINETUNED_SUMMARIZE = "finetuned_summarize"
    RANDROP = "randrop"
    MIGHT_BE_HARMFUL = "might_be_harmful"
    TRANSLATE = "translate"
    TRANSLATE_DUTCH = "translate_dutch"
    TRANSLATE_PORTUGESE = "translate_portugese"
    TRANSLATE_SPANISH = "translate_spanish"
    TRANSLATE_GERMAN = "translate_german"
    TRANSLATE_FRENCH = "translate_french"
    TRANSLATE_ITALIAN = "translate_italian"
    BASE64_ENCODE = "base64_encode"
    BINARY_ENCODE = "binary_encode"
    MORSE_ENCODE = "morse_encode"
    PLEASE = "please"
    LEETSPEAK = "leetspeak"
    EMOJI = "emoji"
    HOMOPHONE = "homophone"
    SYNONYM = "synonym"
    RANDROP_CHARACTER = "randrop_character"
    RANDADD_CHARACTER = "randadd_character"
    REPETITION = "repetition"
    CYRILLIC = "cyrillic"
    ZERO_SPACE_INJECT = "zero_space_inject"
    CASE_SHUFFLE = "case_shuffle"
    PUNCTUATIONSPAM = "punctuationspam"
    LENGTHFATIGUE = "lengthfatigue"